In [1]:
#1. Represent the data in the given sheet into an appropriate NumPy array so
#that you can perform the following actions on it.
import numpy as np

p=np.array([[[[11,8,6,12,7,9,8],[28,32,24,25,28,27,32]],        
                 [[7,10,10,-13,8,14,9],[26,31,25,21,28,30,22]],
                 [[9,6,13,8,6,6,13],[24,30,24,27,25,20,25]],
                 [[13,13,13,6,15,7,9],[29,20,24,23,21,24,29]]],
 
                [[[11,8,11,9,13,11,9],[24,24,24,31,20,23,32]],
                 [[13,7,10,15,13,7,10],[29,29,24,25,28,32,28]],
                 [[8,13,8,8,15,12,11],[30,27,28,21,27,31,25]],
                 [[13,12,15,13,11,7,6],[29,26,30,26,22,32,27]]],

                [[[5,3,4,5,3,3,21],[19,18,18,18,22,2,5]],
                 [[5,6,6,4,7,7,21],[20,18,19,20,20,7,2]],
                 [[7,6,5,7,7,5,19],[20,20,22,18,20,4,3]],
                 [[8,7,6,2,6,4,18],[20,19,22,18,19,4,7]]],
                
                [[[7,10,-10,11,11,11,22],[21,20,19,18,20,71,12]],
                 [[10,7,8,7,10,7,19],[21,22,21,18,20,7,8]],
                 [[10,10,12,7,7,7,21],[20,22,22,21,21,12,12]],
                 [[7,7,8,10,11,12,18],[21,22,21,18,18,10,7]]]])

In [2]:
#2.Write the dimensions and shape of the NumPy array that you have created.
p.shape

(4, 4, 2, 7)

In [3]:
for i in range(4):
     print(p[i,0])

[[11  8  6 12  7  9  8]
 [28 32 24 25 28 27 32]]
[[11  8 11  9 13 11  9]
 [24 24 24 31 20 23 32]]
[[ 5  3  4  5  3  3 21]
 [19 18 18 18 22  2  5]]
[[  7  10 -10  11  11  11  22]
 [ 21  20  19  18  20  71  12]]


In [4]:
#3.Print the daily temperatures for the first week of each month
p[0,0,:,:5]

array([[11,  8,  6, 12,  7],
       [28, 32, 24, 25, 28]])

In [5]:
#4. Print the temperatures for Tuesday of each month
p[:,:,:,1]

array([[[ 8, 32],
        [10, 31],
        [ 6, 30],
        [13, 20]],

       [[ 8, 24],
        [ 7, 29],
        [13, 27],
        [12, 26]],

       [[ 3, 18],
        [ 6, 18],
        [ 6, 20],
        [ 7, 19]],

       [[10, 20],
        [ 7, 22],
        [10, 22],
        [ 7, 22]]])

In [6]:
#5. Print only the maximum temperature for all the weekdays of Dec and Feb.
np.amax(p[1::2,:,1,0:5],axis=2)

array([[31, 29, 30, 30],
       [21, 22, 22, 22]])

In [7]:
np.amax(p[1::2,:,1,0:5],axis=0)

array([[24, 24, 24, 31, 20],
       [29, 29, 24, 25, 28],
       [30, 27, 28, 21, 27],
       [29, 26, 30, 26, 22]])

In [8]:
np.amax(p[1::2,:,1,0:5],axis=1)

array([[30, 29, 30, 31, 28],
       [21, 22, 22, 21, 21]])

In [9]:
s=np.where(p< 0, 0, p)

In [10]:
s

array([[[[11,  8,  6, 12,  7,  9,  8],
         [28, 32, 24, 25, 28, 27, 32]],

        [[ 7, 10, 10,  0,  8, 14,  9],
         [26, 31, 25, 21, 28, 30, 22]],

        [[ 9,  6, 13,  8,  6,  6, 13],
         [24, 30, 24, 27, 25, 20, 25]],

        [[13, 13, 13,  6, 15,  7,  9],
         [29, 20, 24, 23, 21, 24, 29]]],


       [[[11,  8, 11,  9, 13, 11,  9],
         [24, 24, 24, 31, 20, 23, 32]],

        [[13,  7, 10, 15, 13,  7, 10],
         [29, 29, 24, 25, 28, 32, 28]],

        [[ 8, 13,  8,  8, 15, 12, 11],
         [30, 27, 28, 21, 27, 31, 25]],

        [[13, 12, 15, 13, 11,  7,  6],
         [29, 26, 30, 26, 22, 32, 27]]],


       [[[ 5,  3,  4,  5,  3,  3, 21],
         [19, 18, 18, 18, 22,  2,  5]],

        [[ 5,  6,  6,  4,  7,  7, 21],
         [20, 18, 19, 20, 20,  7,  2]],

        [[ 7,  6,  5,  7,  7,  5, 19],
         [20, 20, 22, 18, 20,  4,  3]],

        [[ 8,  7,  6,  2,  6,  4, 18],
         [20, 19, 22, 18, 19,  4,  7]]],


       [[[ 7, 10,  0, 11, 11, 11, 

In [11]:
#6. Print all the days along with the week number in November when the minimum temperature was less than 8 degrees.
c=p[0,:,0,:]
d=np.where(c<8)
print(c[d])

[  6   7   7 -13   6   6   6   6   7]


In [17]:
#7. Print all the weeks in Dec and Jan where the maximum temperature has crossed a threshold of 20 degrees.
r=p[1:3,:,1,:]
r[0,0,0]
x=np.where(r>20)
print("weeks where days have temp greater than 20 in dec and jan")
print()
print('Dec Jan')
for i in range(len(x[0])):
    print(x[0][i],"  ",x[1][i])

weeks where days have temp greater than 20 in dec and jan

Dec Jan
0    0
0    0
0    0
0    0
0    0
0    0
0    1
0    1
0    1
0    1
0    1
0    1
0    1
0    2
0    2
0    2
0    2
0    2
0    2
0    2
0    3
0    3
0    3
0    3
0    3
0    3
0    3
1    0
1    2
1    3


In [18]:
#8. Check if there are any absurd values present in the dataset(like some temp which should not be present in the data)
np.mean(p)

15.504464285714286

In [19]:
#along all axis
np.mean(p,axis=3)

array([[[ 8.71428571, 28.        ],
        [ 6.42857143, 26.14285714],
        [ 8.71428571, 25.        ],
        [10.85714286, 24.28571429]],

       [[10.28571429, 25.42857143],
        [10.71428571, 27.85714286],
        [10.71428571, 27.        ],
        [11.        , 27.42857143]],

       [[ 6.28571429, 14.57142857],
        [ 8.        , 15.14285714],
        [ 8.        , 15.28571429],
        [ 7.28571429, 15.57142857]],

       [[ 8.85714286, 25.85714286],
        [ 9.71428571, 16.71428571],
        [10.57142857, 18.57142857],
        [10.42857143, 16.71428571]]])

In [20]:
np.mean(p[0])

17.267857142857142

In [21]:
#9. What strategy would you use to handle such data points?
iqr=np.percentile(p,75)-np.percentile(p,25)#iqr find karne k liye first half sub second half hoga

In [22]:
iqr

14.25

In [23]:
c=np.mean(p[0])-1.5*iqr
d=np.mean(p[0])+1.5*iqr

In [24]:
c

-4.107142857142858

In [25]:
d

38.64285714285714

In [26]:
np.where(p[0]<c)

(array([1], dtype=int64), array([0], dtype=int64), array([3], dtype=int64))

In [27]:
#10. Find and print the indexes of all the outlier(unusual) values present in the above dataset
np.where(p[0>d])

(array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64))

In [28]:
iqr=np.percentile(p,75)-np.percentile(p,25)
e=np.mean(p[1])-1.5*iqr
f=np.mean(p[1])+1.5*iqr

In [29]:
e

-2.571428571428573

In [30]:
f

40.17857142857143

In [31]:
g=np.mean(p[2])-1.5*iqr
h=np.mean(p[2])+1.5*iqr

In [32]:
g

-10.107142857142858

In [33]:
h

32.64285714285714

In [34]:
i=np.mean(p[3])-1.5*iqr
j=np.mean(p[3])+1.5*iqr

In [35]:
i

-6.696428571428571

In [36]:
j

36.05357142857143

In [37]:
#11.Replace the outliers with an appropriate value.
p[p==24]=5

In [38]:
p

array([[[[ 11,   8,   6,  12,   7,   9,   8],
         [ 28,  32,   5,  25,  28,  27,  32]],

        [[  7,  10,  10, -13,   8,  14,   9],
         [ 26,  31,  25,  21,  28,  30,  22]],

        [[  9,   6,  13,   8,   6,   6,  13],
         [  5,  30,   5,  27,  25,  20,  25]],

        [[ 13,  13,  13,   6,  15,   7,   9],
         [ 29,  20,   5,  23,  21,   5,  29]]],


       [[[ 11,   8,  11,   9,  13,  11,   9],
         [  5,   5,   5,  31,  20,  23,  32]],

        [[ 13,   7,  10,  15,  13,   7,  10],
         [ 29,  29,   5,  25,  28,  32,  28]],

        [[  8,  13,   8,   8,  15,  12,  11],
         [ 30,  27,  28,  21,  27,  31,  25]],

        [[ 13,  12,  15,  13,  11,   7,   6],
         [ 29,  26,  30,  26,  22,  32,  27]]],


       [[[  5,   3,   4,   5,   3,   3,  21],
         [ 19,  18,  18,  18,  22,   2,   5]],

        [[  5,   6,   6,   4,   7,   7,  21],
         [ 20,  18,  19,  20,  20,   7,   2]],

        [[  7,   6,   5,   7,   7,   5,  19],
         [

In [39]:
p[0][p[0]<1]=np.mean(p[0,:,0,:])
p[0][p[0]>0]=np.mean(p[0,:,1,:])

In [40]:
p[0]

array([[[22, 22, 22, 22, 22, 22, 22],
        [22, 22, 22, 22, 22, 22, 22]],

       [[22, 22, 22, 22, 22, 22, 22],
        [22, 22, 22, 22, 22, 22, 22]],

       [[22, 22, 22, 22, 22, 22, 22],
        [22, 22, 22, 22, 22, 22, 22]],

       [[22, 22, 22, 22, 22, 22, 22],
        [22, 22, 22, 22, 22, 22, 22]]])

In [41]:
#12. Find the average max temperature for the winter months in Jaipur
p[:,:,1,:]
q=np.average(p)
np.amax(q)

16.348214285714285

In [42]:
p

array([[[[ 22,  22,  22,  22,  22,  22,  22],
         [ 22,  22,  22,  22,  22,  22,  22]],

        [[ 22,  22,  22,  22,  22,  22,  22],
         [ 22,  22,  22,  22,  22,  22,  22]],

        [[ 22,  22,  22,  22,  22,  22,  22],
         [ 22,  22,  22,  22,  22,  22,  22]],

        [[ 22,  22,  22,  22,  22,  22,  22],
         [ 22,  22,  22,  22,  22,  22,  22]]],


       [[[ 11,   8,  11,   9,  13,  11,   9],
         [  5,   5,   5,  31,  20,  23,  32]],

        [[ 13,   7,  10,  15,  13,   7,  10],
         [ 29,  29,   5,  25,  28,  32,  28]],

        [[  8,  13,   8,   8,  15,  12,  11],
         [ 30,  27,  28,  21,  27,  31,  25]],

        [[ 13,  12,  15,  13,  11,   7,   6],
         [ 29,  26,  30,  26,  22,  32,  27]]],


       [[[  5,   3,   4,   5,   3,   3,  21],
         [ 19,  18,  18,  18,  22,   2,   5]],

        [[  5,   6,   6,   4,   7,   7,  21],
         [ 20,  18,  19,  20,  20,   7,   2]],

        [[  7,   6,   5,   7,   7,   5,  19],
         [

In [43]:
q

16.348214285714285

In [44]:
#13. Find the weekly min avg temp for the month of Dec in Jaipur
m=np.average(p)
np.amin(m)

16.348214285714285

In [45]:
m

16.348214285714285

In [46]:
#14. Find the overall avg temp for the months Dec and Jan
n=np.average(p,1)

In [47]:
n

array([[[22.  , 22.  , 22.  , 22.  , 22.  , 22.  , 22.  ],
        [22.  , 22.  , 22.  , 22.  , 22.  , 22.  , 22.  ]],

       [[11.25, 10.  , 11.  , 11.25, 13.  ,  9.25,  9.  ],
        [23.25, 21.75, 17.  , 25.75, 24.25, 29.5 , 28.  ]],

       [[ 6.25,  5.5 ,  5.25,  4.5 ,  5.75,  4.75, 19.75],
        [19.75, 18.75, 20.25, 18.5 , 20.25,  4.25,  4.25]],

       [[ 8.5 ,  8.5 ,  4.5 ,  8.75,  9.75,  9.25, 20.  ],
        [20.75, 21.5 , 20.75, 18.75, 19.75, 25.  ,  9.75]]])

In [48]:
o=np.average(p,2)

In [49]:
o

array([[[22. , 22. , 22. , 22. , 22. , 22. , 22. ],
        [22. , 22. , 22. , 22. , 22. , 22. , 22. ],
        [22. , 22. , 22. , 22. , 22. , 22. , 22. ],
        [22. , 22. , 22. , 22. , 22. , 22. , 22. ]],

       [[ 8. ,  6.5,  8. , 20. , 16.5, 17. , 20.5],
        [21. , 18. ,  7.5, 20. , 20.5, 19.5, 19. ],
        [19. , 20. , 18. , 14.5, 21. , 21.5, 18. ],
        [21. , 19. , 22.5, 19.5, 16.5, 19.5, 16.5]],

       [[12. , 10.5, 11. , 11.5, 12.5,  2.5, 13. ],
        [12.5, 12. , 12.5, 12. , 13.5,  7. , 11.5],
        [13.5, 13. , 13.5, 12.5, 13.5,  4.5, 11. ],
        [14. , 13. , 14. , 10. , 12.5,  4. , 12.5]],

       [[14. , 15. ,  4.5, 14.5, 15.5, 41. , 17. ],
        [15.5, 14.5, 14.5, 12.5, 15. ,  7. , 13.5],
        [15. , 16. , 17. , 14. , 14. ,  9.5, 16.5],
        [14. , 14.5, 14.5, 14. , 14.5, 11. , 12.5]]])

In [50]:
np.amin(n)

4.25

In [51]:
np.amin(o)

2.5

In [52]:
p[1:2,:,:,:]
np.amin(p)

-10

In [53]:
np.amax(p)

71

In [54]:
#15. Find the least temp experienced by the city in the month of Dec and Jan. Also print the exact date( Day/Week/Month) for the same.
k=np.min(p[1:3,:,:,:])
m1={0:"nov",1:"dec",2:"jan",3:"feb"}
w1={0:"week(1)",1:"week(2)",2:"week(3)",3:"week(4)"}
d1={0:"monday",1:"tuesday",2:"wednesday",3:"thrusday",4:"friday",5:"saturday",6:"sunday"}



z=np.where(p[1:3,:,:,:]==k)
z

for i in range(len(z[0])):
    print(m1[z[0][i]]," ",w1[z[1][i]]," ",d1[z[3][i]])

dec   week(1)   saturday
dec   week(2)   sunday
dec   week(4)   thrusday


In [55]:
#16. Find the max temp in the month of Feb and return its date(Day/Week/Month
p[3,:,1,:]

array([[21, 20, 19, 18, 20, 71, 12],
       [21, 22, 21, 18, 20,  7,  8],
       [20, 22, 22, 21, 21, 12, 12],
       [21, 22, 21, 18, 18, 10,  7]])

In [56]:
#maximum temp of februry month
np.amax(p)

71

In [57]:
#17. Find the days in the month of Nov where the max temp of the day dropped below the avg temp of the month. As
d=np.average(p)

In [58]:
d

16.348214285714285

In [59]:
#18th Convert the above dataset into an array where the weeks of the same 
#month must be present in the same row, but belonging to different months
#should come in a row either below or above the selected month
p[:,:,:,:]
np.transpose(p)

array([[[[ 22,  11,   5,   7],
         [ 22,  13,   5,  10],
         [ 22,   8,   7,  10],
         [ 22,  13,   8,   7]],

        [[ 22,   5,  19,  21],
         [ 22,  29,  20,  21],
         [ 22,  30,  20,  20],
         [ 22,  29,  20,  21]]],


       [[[ 22,   8,   3,  10],
         [ 22,   7,   6,   7],
         [ 22,  13,   6,  10],
         [ 22,  12,   7,   7]],

        [[ 22,   5,  18,  20],
         [ 22,  29,  18,  22],
         [ 22,  27,  20,  22],
         [ 22,  26,  19,  22]]],


       [[[ 22,  11,   4, -10],
         [ 22,  10,   6,   8],
         [ 22,   8,   5,  12],
         [ 22,  15,   6,   8]],

        [[ 22,   5,  18,  19],
         [ 22,   5,  19,  21],
         [ 22,  28,  22,  22],
         [ 22,  30,  22,  21]]],


       [[[ 22,   9,   5,  11],
         [ 22,  15,   4,   7],
         [ 22,   8,   7,   7],
         [ 22,  13,   2,  10]],

        [[ 22,  31,  18,  18],
         [ 22,  25,  20,  18],
         [ 22,  21,  18,  21],
         [ 22,  26,

In [60]:
#19.The above data is appropriate for an audience who follow the metric
#system of measurement. Create an array that holds the same data but
#presented in Fahrenheit
celcius=p
fahrenheit=(celcius*1.8)-32
print("Temperature in fahrenheit:",fahrenheit)

Temperature in fahrenheit: [[[[  7.6   7.6   7.6   7.6   7.6   7.6   7.6]
   [  7.6   7.6   7.6   7.6   7.6   7.6   7.6]]

  [[  7.6   7.6   7.6   7.6   7.6   7.6   7.6]
   [  7.6   7.6   7.6   7.6   7.6   7.6   7.6]]

  [[  7.6   7.6   7.6   7.6   7.6   7.6   7.6]
   [  7.6   7.6   7.6   7.6   7.6   7.6   7.6]]

  [[  7.6   7.6   7.6   7.6   7.6   7.6   7.6]
   [  7.6   7.6   7.6   7.6   7.6   7.6   7.6]]]


 [[[-12.2 -17.6 -12.2 -15.8  -8.6 -12.2 -15.8]
   [-23.  -23.  -23.   23.8   4.    9.4  25.6]]

  [[ -8.6 -19.4 -14.   -5.   -8.6 -19.4 -14. ]
   [ 20.2  20.2 -23.   13.   18.4  25.6  18.4]]

  [[-17.6  -8.6 -17.6 -17.6  -5.  -10.4 -12.2]
   [ 22.   16.6  18.4   5.8  16.6  23.8  13. ]]

  [[ -8.6 -10.4  -5.   -8.6 -12.2 -19.4 -21.2]
   [ 20.2  14.8  22.   14.8   7.6  25.6  16.6]]]


 [[[-23.  -26.6 -24.8 -23.  -26.6 -26.6   5.8]
   [  2.2   0.4   0.4   0.4   7.6 -28.4 -23. ]]

  [[-23.  -21.2 -21.2 -24.8 -19.4 -19.4   5.8]
   [  4.    0.4   2.2   4.    4.  -19.4 -28.4]]

  [[-19.4

In [61]:
#20. Sort the above data in descending order on the basis of weekly average
#for the month of Dec.
a=np.average(p[1,0])
b=np.average(p[1,1]) 
c=np.average(p[1,2])
d=np.average(p[1,3]) 
print(a)
print(b)
print(c)
print(d)

13.785714285714286
17.928571428571427
18.857142857142858
19.214285714285715


In [62]:
u=np.array([a,b,c,d])
u

array([13.78571429, 17.92857143, 18.85714286, 19.21428571])

In [63]:
np.sort(u)[::-1]

array([19.21428571, 18.85714286, 17.92857143, 13.78571429])

In [64]:
#21. Sort the temp of the first three days of each month in descending order on the basis of overall average for the whole winter.
a=np.average(p[0,:,:,0:3])
b=np.average(p[1,:,:,0:3])
c=np.average(p[2,:,:,0:3])
d=np.average(p[3,:,:,0:3])
print(a)
print(b)
print(c)
print(d)

22.0
15.708333333333334
12.625
14.083333333333334


In [65]:
a=np.average(p[:,:,0:3])
a

16.348214285714285

In [66]:
x=np.array([a,b,c,d])
x

array([16.34821429, 15.70833333, 12.625     , 14.08333333])

In [67]:
np.sort(x)[::-1]

array([16.34821429, 15.70833333, 14.08333333, 12.625     ])

In [68]:
#22. Create an array that stores the difference between the min and max temp for each day in all the winter months.x=p[:,:,0,:]
y=p[:,:,1,:]
dif=y-x
print(dif)

[[[  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]]

 [[ -6  -3  -6  22   7  12  23]
  [ 16  22  -5  10  15  25  18]
  [ 22  14  20  13  12  19  14]
  [ 16  14  15  13  11  25  21]]

 [[ 14  15  14  13  19  -1 -16]
  [ 15  12  13  16  13   0 -19]
  [ 13  14  17  11  13  -1 -16]
  [ 12  12  16  16  13   0 -11]]

 [[ 14  10  29   7   9  60 -10]
  [ 11  15  13  11  10   0 -11]
  [ 10  12  10  14  14   5  -9]
  [ 14  15  13   8   7  -2 -11]]]


In [69]:
#23. Find and store the difference between the max temp of two consecutive
#days for each month of winter season.
k=p[:,:,1,:]
arr=np.diff(k,axis=2)
print(arr)

[[[  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]]

 [[  0   0  26 -11   3   9]
  [  0 -24  20   3   4  -4]
  [ -3   1  -7   6   4  -6]
  [ -3   4  -4  -4  10  -5]]

 [[ -1   0   0   4 -20   3]
  [ -2   1   1   0 -13  -5]
  [  0   2  -4   2 -16  -1]
  [ -1   3  -4   1 -15   3]]

 [[ -1  -1  -1   2  51 -59]
  [  1  -1  -3   2 -13   1]
  [  2   0  -1   0  -9   0]
  [  1  -1  -3   0  -8  -3]]]


In [70]:
#24. Find and store the difference between the minimum temp of two
#consecutive days for each month of the winter season.
o=p[:,:,0,:]
arr=np.diff(k,axis=2)
print(arr)

[[[  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]]

 [[  0   0  26 -11   3   9]
  [  0 -24  20   3   4  -4]
  [ -3   1  -7   6   4  -6]
  [ -3   4  -4  -4  10  -5]]

 [[ -1   0   0   4 -20   3]
  [ -2   1   1   0 -13  -5]
  [  0   2  -4   2 -16  -1]
  [ -1   3  -4   1 -15   3]]

 [[ -1  -1  -1   2  51 -59]
  [  1  -1  -3   2 -13   1]
  [  2   0  -1   0  -9   0]
  [  1  -1  -3   0  -8  -3]]]


In [71]:
#25. Create an array by combining the data present in arrays created in q.23
#and q.24, to store the difference between the min and max temp of each
#day of all the months for the whole winter season, in a single array.
add_array=np.concatenate([o,k])
add_array.flatten()

array([ 22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,
        22,  22,  11,   8,  11,   9,  13,  11,   9,  13,   7,  10,  15,
        13,   7,  10,   8,  13,   8,   8,  15,  12,  11,  13,  12,  15,
        13,  11,   7,   6,   5,   3,   4,   5,   3,   3,  21,   5,   6,
         6,   4,   7,   7,  21,   7,   6,   5,   7,   7,   5,  19,   8,
         7,   6,   2,   6,   4,  18,   7,  10, -10,  11,  11,  11,  22,
        10,   7,   8,   7,  10,   7,  19,  10,  10,  12,   7,   7,   7,
        21,   7,   7,   8,  10,  11,  12,  18,  22,  22,  22,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  22,  22,   5,   5,   5,
        31,  20,  23,  32,  29,  29,   5,  25,  28,  32,  28,  30,  27,
        28,  21,  27,  31,  25,  29,  26,  30,  26,  22,  32,  27,  19,
        18,  18,  18,  22,   2,   5,  20,  18,  19,  20,  20,   